---
permalink: csharp/exceptions/kwidgzwzz
title: C# program to demonstrate the use of try and catch blocks
---

<div class="codecard">C# NullReferenceException</div>
<div class="card">{{ site.csfile }}</div>
<pre class="code">{%- highlight csharp -%}
string s = null;
Console.WriteLine(s.Length);
{%- endhighlight -%}</pre>
<div class="card">{{ site.output }}</div>
<span><pre>
{{ site.runcs }}
<error>Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
    at Program.&lt;Main>$(String[] args) in /home/kodingwindow/csharp/Program.cs:line 2</error> 
kodingwindow@kw:~/csharp$ 
</pre></span>

<div class="codecard">{{ page.title }}</div>
<div class="card">{{ site.csfile }}</div>
<pre class="code">{%- highlight csharp -%}
try
{
    string s = null;
    Console.WriteLine(s.Length);
}
catch(NullReferenceException e)
{
    Console.WriteLine("String is null, hence, unable to find the length.");
}
{%- endhighlight -%}</pre>
<div class="card">{{ site.output }}</div>
<span><pre>
{{ site.runcs }}
String is null, hence, unable to find the length.
kodingwindow@kw:~/csharp$ 
</pre></span>

<div class="codecard">C# program to demonstrate the use of try with multiple catch blocks</div>
<div class="card">{{ site.csfile }}</div>
<pre class="code">{%- highlight csharp -%}
try
{
    string s = null;
    Console.WriteLine(s.Length);
}
catch(InvalidOperationException e)
{
    Console.WriteLine("Exception caught in the first catch block");
}
catch(NullReferenceException e)
{
    Console.WriteLine("Exception caught in the second catch block");
}
{%- endhighlight -%}</pre>
<div class="card">{{ site.output }}</div>
<span><pre>
{{ site.runcs }}
Exception caught in the second catch block
kodingwindow@kw:~/csharp$ 
</pre></span>