---
permalink: csharp/exceptions/kwidkwdvv
title: C# program to demonstrate the use of nested try and catch blocks
---

<div class="codecard">{{ page.title }}</div>
<div class="card">{{ site.csfile }}</div>
<pre class="code">{% highlight csharp %}
int a = 1, b = 0;
try
{
    try
    {
        Console.WriteLine(a / b);
    }
    catch (Exception e)
    {
        Console.WriteLine("First Exception: " + e.ToString());
    }
    string s = null;
    Console.WriteLine(s.Length);

}
catch (Exception e)
{
    Console.WriteLine("Second Exception: " + e.ToString());
}
{% endhighlight %}</pre>
<div class="card">{{ site.output }}</div>
<span><pre>
{{ site.runcs }}
<error>First Exception: System.DivideByZeroException: Attempted to divide by zero.
    at Program.&lt;Main>$(String[] args) in /home/kodingwindow/csharp/Program.cs:line 6
 Second Exception: System.NullReferenceException: Object reference not set to an instance of an object.
    at Program.&lt;Main>$(String[] args) in /home/kodingwindow/csharp/Program.cs:line 13</error> 
kodingwindow@kw:~/csharp$ 
</pre></span>

<div class="codecard">{{ page.title }}</div>
<div class="card">{{ site.csfile }}</div>
<pre class="code">{% highlight csharp %}
string s = null;
int n = 515, d = 0, result = 0;
try
{
    Console.WriteLine("Length: " + s.Length);
}
catch (InvalidOperationException e)
{
    Console.WriteLine("Exception caught in the first catch block");
}
catch (Exception e1)
{
    try
    {
        result = n / d;
    }
    catch (DivideByZeroException e2)
    {
        Console.WriteLine("Exception caught in the first nested catch block");
    }
    Console.WriteLine("Exception caught in the third catch block");
}
{% endhighlight %}</pre>
<div class="card">{{ site.output }}</div>
<span><pre>
{{ site.runcs }}
Exception caught in the first nested catch block
Exception caught in the third catch block
kodingwindow@kw:~/csharp$ 
</pre></span>